//! HsmSession access-control tests — HSM-REQ-037/038/039.
//!
//! These tests use the SoftwareBackend but exercise the session layer:
//! handle ownership enforcement, rate-limit counters, and IDS event emission.

use scorehsm_host::{
    backend::{sw::SoftwareBackend, HsmBackend},
    ids::{IdsEvent, IdsHook, NullIds},
    session::{HsmSession, OpLimit, RateLimits},
    types::KeyType,
};
use std::sync::{Arc, Mutex};

// ── Test IDS hook ─────────────────────────────────────────────────────────────

#[derive(Clone, Default)]
struct RecordingIds {
    events: Arc<Mutex<Vec<String>>>,
}

impl RecordingIds {
    fn events(&self) -> Vec<String> {
        self.events.lock().unwrap().clone()
    }
}

impl IdsHook for RecordingIds {
    fn on_event(&self, event: IdsEvent) {
        self.events.lock().unwrap().push(format!("{:?}", event));
    }
}

fn make_session() -> HsmSession {
    let b = SoftwareBackend::new();
    let mut s = HsmSession::new(b);
    s.init().unwrap();
    s
}

// ── Ownership tests ───────────────────────────────────────────────────────────

/// A handle generated by a session can be used by the same session.
#[test]
fn test_session_own_handle_allowed() {
    let mut s = make_session();
    let h = s.key_generate(KeyType::Aes256).unwrap();
    let digest = s.sha256(b"hello").unwrap();
    // Just verify no error — key belongs to this session
    let iv = [0u8; 12];
    let params = scorehsm_host::types::AesGcmParams { iv: &iv, aad: b"" };
    assert!(s.aes_gcm_encrypt(h, &params, b"plaintext").is_ok());
}

/// Using a handle value that was never generated returns InvalidKeyHandle.
#[test]
fn test_session_foreign_handle_rejected() {
    use scorehsm_host::error::HsmError;
    use scorehsm_host::types::KeyHandle;
    let mut s = make_session();
    let foreign = KeyHandle(0xDEADBEEF);
    let result = s.hmac_sha256(foreign, b"data");
    assert!(matches!(result, Err(HsmError::InvalidKeyHandle)));
}

/// key_delete removes the handle from ownership.
#[test]
fn test_session_deleted_handle_rejected() {
    use scorehsm_host::error::HsmError;
    let mut s = make_session();
    let h = s.key_generate(KeyType::HmacSha256).unwrap();
    s.key_delete(h).unwrap();
    let result = s.hmac_sha256(h, b"data");
    assert!(matches!(result, Err(HsmError::InvalidKeyHandle)));
}

// ── IDS event tests ───────────────────────────────────────────────────────────

/// key_generate emits KeyGenerated event.
#[test]
fn test_ids_key_generated_event() {
    let recorder = RecordingIds::default();
    let b = SoftwareBackend::new();
    let mut s = HsmSession::new(b)
        .with_ids_hook(Box::new(recorder.clone()));
    s.init().unwrap();
    s.key_generate(KeyType::EccP256).unwrap();
    let events = recorder.events();
    assert!(events.iter().any(|e| e.contains("KeyGenerated")));
}

/// key_delete emits KeyDeleted event.
#[test]
fn test_ids_key_deleted_event() {
    let recorder = RecordingIds::default();
    let b = SoftwareBackend::new();
    let mut s = HsmSession::new(b)
        .with_ids_hook(Box::new(recorder.clone()));
    s.init().unwrap();
    let h = s.key_generate(KeyType::Aes256).unwrap();
    s.key_delete(h).unwrap();
    let events = recorder.events();
    assert!(events.iter().any(|e| e.contains("KeyDeleted")));
}

/// ecdsa_sign emits EcdsaSigned event.
#[test]
fn test_ids_ecdsa_signed_event() {
    let recorder = RecordingIds::default();
    let b = SoftwareBackend::new();
    let mut s = HsmSession::new(b)
        .with_ids_hook(Box::new(recorder.clone()));
    s.init().unwrap();
    let h = s.key_generate(KeyType::EccP256).unwrap();
    let digest = s.sha256(b"message").unwrap();
    s.ecdsa_sign(h, &digest).unwrap();
    let events = recorder.events();
    assert!(events.iter().any(|e| e.contains("EcdsaSigned")));
}

// ── Rate limit tests ──────────────────────────────────────────────────────────

/// Exceeding the sign rate limit returns an error.
#[test]
fn test_rate_limit_sign_exceeded() {
    use scorehsm_host::error::HsmError;
    let b = SoftwareBackend::new();
    let limits = RateLimits {
        sign:    OpLimit::new(2, 60),   // only 2 signs allowed per minute
        decrypt: OpLimit::new(100, 60),
        random:  OpLimit::new(100, 60),
        derive:  OpLimit::new(100, 60),
    };
    let mut s = HsmSession::new(b)
        .with_rate_limits(limits);
    s.init().unwrap();
    let h = s.key_generate(KeyType::EccP256).unwrap();
    let digest = s.sha256(b"msg").unwrap();

    assert!(s.ecdsa_sign(h, &digest).is_ok()); // 1st — ok
    assert!(s.ecdsa_sign(h, &digest).is_ok()); // 2nd — ok
    let result = s.ecdsa_sign(h, &digest);     // 3rd — should fail
    assert!(matches!(result, Err(HsmError::UsbError(_))));
}
